# Generated by Django 4.0.3 on 2022-03-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='alan_ogrenciler_json',
            field=models.JSONField(null=True, verbose_name='Kitabı Alan Öğrenciler jsonf'),
        ),
    ]
