# Generated by Django 4.0.3 on 2022-03-13 19:23

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kitap', '0002_alter_book_alan_ogrenciler_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='alan_ogrenciler_json',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
