# Generated by Django 4.0.3 on 2022-03-14 13:02

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kitap', '0005_alter_book_alan_og_alter_book_alis_tar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='alan_ogrenciler_json',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Kitabı daha önce ödünç almış öğrenciler (Program Kendi dolduracak)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='alis_tar',
            field=models.DateField(blank=True, null=True, verbose_name='Kitabın Verilme Tarihi (Program Kendi dolduracak)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_date',
            field=models.DateField(blank=True, null=True, verbose_name='Kitabın Yayınlanma Tarihi (Sorumlu kisi doldurmalı)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_writer',
            field=models.CharField(max_length=100, verbose_name='Kitabın Yazarı (Sorumlu kisi doldurmalı)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='teslim_tar',
            field=models.DateField(blank=True, null=True, verbose_name='Kitabın Teslim Tarihi (Program Kendi dolduracak)'),
        ),
    ]
