# Generated by Django 4.0.3 on 2022-03-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitap', '0006_alter_book_alan_ogrenciler_json_alter_book_alis_tar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='alan_og',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Kitabı Alan Ogrenci (Program Kendi dolduracak)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(max_length=100, verbose_name='Kitabın Adı (Sorumlu kisi doldurmalı)'),
        ),
    ]
