# Generated by Django 4.0.3 on 2022-04-07 15:22

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kitap', '0007_alter_book_alan_og_alter_book_book_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idler', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Kitapların IDleri (Program Kendi dolduracak)')),
            ],
        ),
    ]
