# Generated by Django 4.0.3 on 2022-04-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitap', '0009_book_book_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_tag',
            field=models.CharField(blank=True, choices=[('0', 'İslami'), ('1', 'Felsefe'), ('2', 'Tarih'), ('3', 'Biyografi'), ('4', 'Hikaye')], max_length=20, null=True, verbose_name='Books Tag'),
        ),
    ]
