# Generated by Django 4.0.3 on 2022-04-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitap', '0010_alter_book_book_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_tag',
            field=models.CharField(blank=True, choices=[('islami', 'İslami'), ('felsefe', 'Felsefe'), ('tarih', 'Tarih'), ('biyografi', 'Biyografi'), ('deneme', 'Deneme'), ('edebiyat', 'Edebiyat'), ('yabancı dil', 'Yabancı Dil'), ('fen bilimleri', 'Fen bilimleri'), ('roman', 'Roman'), ('din', 'Din')], max_length=20, null=True, verbose_name='Kitabın Kategorisi (Sorumlu kişi doldurmalı'),
        ),
    ]
